import Link from "next/link"
import "./globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
  <html lang="en">
  <body>
    <header>
      <div className="navbar">
        <Link href="/">홈</Link>
        <Link href="/login">login</Link>
      </div>  
    </header>
    {children}
  </body>
    <footer className="footer">
      <p>Footer</p>
    </footer>
</html>
  )
}
